# Generated by Django 2.2.2 on 2019-06-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_cooperativeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=70),
        ),
    ]
